version: '3.8'
services:
  svelte:
    env_file:
      - .env
    build: .
    command: node -r dotenv/config build
    ports:
      - 81:3000

  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - svelte